// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                            3
// Async Callback:                       1
// Total number of exported functions:   6

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    citizen
    (
        init => init
        upgrade => upgrade
        mintCitizen => mint_citizen
        claimCitizen => claim_citizen
        issue => issue_citizen_token
    )
}

multiversx_sc_wasm_adapter::async_callback! { citizen }
