// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                            5
// Async Callback:                       1
// Total number of exported functions:   8

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    blacksmith
    (
        init => init
        upgrade => upgrade
        mintShield => mint_shield
        claimShield => claim_shield
        mintSword => mint_sword
        claimSword => claim_sword
        issue => issue_tool_token
    )
}

multiversx_sc_wasm_adapter::async_callback! { blacksmith }
