// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                            4
// Async Callback:                       1
// Total number of exported functions:   7

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    staking
    (
        init => init
        upgrade => upgrade
        stakeTokenWinter => stake_token_winter
        claimRewards => claim_rewards
        setRewardRecipient => set_reward_recipient
        issueToken => issue_token
    )
}

multiversx_sc_wasm_adapter::async_callback! { staking }
