// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                            6
// Async Callback:                       1
// Total number of exported functions:   8

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    staking
    (
        init => init
        stakeTokenWinter => stake_token_winter
        changeRewardsRecipient => change_rewards_recipient
        lockedTokenAmount => locked_token_amount
        lockedTokens => locked_tokens
        getRewardTokenId => reward_token_id
        getRewardsRecipient => rewards_recipient
    )
}

multiversx_sc_wasm_adapter::async_callback! { staking }
