// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                            5
// Async Callback (empty):               1
// Total number of exported functions:   8

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    staking
    (
        init => init
        upgrade => upgrade
        stakeTokenWinter => stake_token_winter
        getMinStakeEpochs => get_min_stake_epochs
        getStakeDuration => get_stake_duration
        lockedTokenAmount => locked_token_amount
        lockedTokens => locked_tokens
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
