// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                            6
// Async Callback:                       1
// Total number of exported functions:   8

#![no_std]
#![allow(internal_features)]
#![feature(lang_items)]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    snow
    (
        init => init
        upgrade => upgrade
        issueTokenSnow => issue_token
        burnTokens => burn_tokens
        getAllUsersTokens => get_all_user_tokens
        getAllUserTokenBalances => get_all_user_token_balances
        getSingleTokenBalance => get_single_token_balance
    )
}

multiversx_sc_wasm_adapter::async_callback! { snow }
